Document: drvfgpdb
Title: Debian drvfgpdb Manual
Author: <insert document author here>
Abstract: This manual describes what drvfgpdb is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/drvfgpdb/drvfgpdb.sgml.gz

Format: postscript
Files: /usr/share/doc/drvfgpdb/drvfgpdb.ps.gz

Format: text
Files: /usr/share/doc/drvfgpdb/drvfgpdb.text.gz

Format: HTML
Index: /usr/share/doc/drvfgpdb/html/index.html
Files: /usr/share/doc/drvfgpdb/html/*.html
